# Azure pipeline used to trigger builds of the JPO SDW Depositor project
# This pipeline is primarily used for CI in the CDOT-CV fork

trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - 'src/*'

pool:
  vmImage: ubuntu-latest

steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        **
        !**/docs/**
        !**/*.md
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # Publish the artifacts directory for consumption in publish pipeline
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'jpo-sdw-depositor'
      publishLocation: 'Container'
