name: CI
on: 
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [develop, master, fix_sonarcloud_metric]
    
jobs:
  jpo-sdw-depositor:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:21-jdk-alpine
      options: --user root
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v6
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Build
        run: mvn -e clean verify
      - name: Archive code coverage results
        uses: actions/upload-artifact@v6
        with:
          name: jpo-sdw-depositor
          path: target
          if-no-files-found: error
  sonar:
    needs: [jpo-sdw-depositor]
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Download code coverage results
        uses: actions/download-artifact@v7
        with:
          name: jpo-sdw-depositor
          path: target
      - name: SonarScanner
        uses: usdot-fhwa-stol/actions/sonar-scanner@main
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          working-dir: ${{ github.workspace }}